/**
 * Import project figures from their source repositories into src/assets/.
 *
 * Source:  AutoCarto-Agent (CartoLLM) — output/figures/, generated by
 *          scripts/gen_results_panel.py and scripts/gen_architecture_diagram.py in that repo.
 * License: the owner's own work; committed here as portfolio assets.
 * Output:  src/assets/projects/<slug>/*.png  (Astro's <Image> handles webp/avif + srcset)
 *          plus a 1200x630 thumbnail used for both the project card and og:image (§6.4).
 *
 * Figures are downscaled to 2400px on the long edge — 2x the widest display size (§8.1),
 * not the 5370px originals. Re-run after regenerating figures upstream:
 *   node scripts/import-figures.mjs
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const CARTOLLM = 'C:/Users/abdul/Desktop/Temporary Files/RUTGERS/Portfolio Projects/CartoLLM';

/** @type {{slug: string, from: string, files: string[], thumbnail: {file: string, position?: string}}[]} */
const JOBS = [
  {
    slug: 'autocarto-agent',
    from: path.join(CARTOLLM, 'output/figures'),
    files: [
      'architecture_boundary.png',
      'atlanta_results_panel.png',
      'ungated_vs_gated.png',
      'rejection_sankey.png',
      'threshold_sensitivity.png',
      'gate2_distribution_diagnostics.png',
    ],
    thumbnail: { file: 'atlanta_results_panel.png', position: 'top' },
  },
];

const MAX_EDGE = 2400;
const THUMB = { width: 1200, height: 630 };

async function run() {
  for (const job of JOBS) {
    const outDir = path.resolve('src/assets/projects', job.slug);
    await mkdir(outDir, { recursive: true });

    for (const file of job.files) {
      const src = path.join(job.from, file);
      if (!existsSync(src)) {
        console.warn(`  ! missing source, skipped: ${src}`);
        continue;
      }
      const dest = path.join(outDir, file);
      await sharp(await readFile(src))
        .resize({ width: MAX_EDGE, height: MAX_EDGE, fit: 'inside', withoutEnlargement: true })
        .png({ compressionLevel: 9, palette: false })
        .toFile(dest);
      const { size } = await sharp(dest).metadata();
      console.log(`  ${job.slug}/${file} (${Math.round((size ?? 0) / 1024)} KB)`);
    }

    const thumbSrc = path.join(job.from, job.thumbnail.file);
    if (existsSync(thumbSrc)) {
      const thumbOut = path.join(outDir, 'thumbnail.png');
      await sharp(await readFile(thumbSrc))
        .resize({
          ...THUMB,
          fit: 'cover',
          position: job.thumbnail.position ?? 'centre',
        })
        .png({ compressionLevel: 9 })
        .toFile(thumbOut);
      console.log(`  ${job.slug}/thumbnail.png (1200x630)`);
    }
  }
}

await run();
await writeFile(
  path.resolve('src/assets/projects/.imported'),
  `${new Date().toISOString()}\n`,
  'utf8'
);
console.log('done');
